# Generated by Django 3.1.6 on 2021-02-15 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField(max_length=2)),
                ('descripcion', models.TextField(max_length=300)),
                ('tamanio', models.CharField(max_length=15)),
                ('foto', models.CharField(max_length=60)),
                ('raza', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('contrasenia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perdido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_perdido', models.DateField()),
                ('valido_hasta', models.DateField()),
                ('siencontrado', models.BooleanField()),
                ('fecha_encontrado', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdido.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdido.usuario'),
        ),
    ]
