# Generated by Django 3.1.6 on 2021-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(max_length=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamanio',
            field=models.CharField(max_length=15, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
